### ISSUE TITLE
No longer possible to check out the version that works with QEMU master

### ISSUE THREAD

**Issue by sorear** [sifive/freedom-u-sdk#1]
I know this isn't the intended use of this repository but the recent rebasing on sifive/riscv-linux make `git submodule update` fail for sifive/freedom-u-sdk@5d38ed:

```
fatal: reference is not a tree: 3989911d0071b93d2e529d22007b7ec783a57532
Unable to checkout '3989911d0071b93d2e529d22007b7ec783a57532' in submodule path 'linux'
```

(5d38ed is the last priv-1.9 freedom-u-sdk; the current rev is priv-1.9.1, which is not supported by qemu.)

**Comment by a0u** [comment]
I have restored commit sifive/riscv-linux@3989911d0071b93d2e529d22007b7ec783a57532 as tag `freedom-u-sdk-20161128`.

**Comment by sorear** [comment]
Thanks!  It builds now.
