### ISSUE TITLE
Makefile:123: *** multiple target patterns.  Stop.

### ISSUE THREAD

**Issue by tromedo** [sifive/freedom-u-sdk#117]
Hey Guys,

I just executed "make sim" to run linux in spike and I got the error: Makefile:123: *** multiple target patterns.  Stop.

How do I fix this? Sorry noob here.

**Comment by jim-wilson** [comment]
make sim isn't supported at the moment.  spike lacks the driver support necessary to run u-boot.  make qemu still works.  If you really need make sim, then check out the legacy v1_0 branch, though this will give you old versions of everything.

I don't know how you got the multiple target patterns error though.  123 is a line number in the makefile.  Did you accidentally modify it perhaps?

**Comment by tromedo** [comment]
> make sim isn't supported at the moment. spike lacks the driver support necessary to run u-boot. make qemu still works. If you really need make sim, then check out the legacy v1_0 branch, though this will give you old versions of everything.
> 
> I don't know how you got the multiple target patterns error though. 123 is a line number in the makefile. Did you accidentally modify it perhaps?

Yeah, I am using version 1_0 branch only.

I didn't change the makefile. But I disabled virtual console in Linux folder using make menuconfig. Because Linux boot stopped at "Bootconsole[early0] disabled". Even though the line "CONFIG_HVC_RISCV_SBI=y" is there.

**Comment by jim-wilson** [comment]
It works for me on Ubuntu 16.04.  I don't need any change other than turning on CONFIG_HVC_RISCV_SBI.

**Comment by tprrt** [comment]
This issue is no longer relevant.
