### ISSUE TITLE
Cannot insert kernel module "openvswitch.ko"

### ISSUE THREAD

**Issue by gaomei052** [sifive/freedom-u-sdk#122]
openvswitch: target ffffffe0000342d8 can not be addressed by the 32-bit offset from PC = 00000000b5af5b3d
insmod: ERROR: could not insert module openvswitch.ko: Invalid parameters

**Comment by tmagik** [comment]
What kernel version and/or freedom-u-sdk git tag did you build this from?

**Comment by gaomei052** [comment]
The clone commmand I used is "https://github.com/sifive/freedom-u-sdk.git & git submodule update --recursive --init"，I don't clone specified tag.The kernel version is 4.19.0.I build it,not error.No errors with other imports.nsh.ko & libcrc32c.ko is insert

**Comment by tprrt** [comment]
This issue is no longer relevant.
