### ISSUE TITLE
Error when try to boot from flash on board(execute instructions from flash directly)

### ISSUE THREAD

**Issue by chaican** [sifive/freedom-u-sdk#125]
As README.md under root directory said, I flash the hifive-unleashed-a00-YYYY-MM-DD.gpt image into the QSPI flash, and then switch MODESEL pin to 0110(which is said will resuce image from flash), but i got error:

MMC_SPI: 0 at 0:1 hz 20000000 mode 0

Warning: Input data exceeds 1048576 bytes - truncated
Info: input data size = 1048578 = 0x100002
Error: Environment import failed: errno = 12
running boot2…

Error: “boot2” not defined

Is there something i did wrong? How  can i fix this issue, or is there any possible way can boot kernel(execute instruction from flash directly, not read image from flash to ram) from flash on HiFive unleashed board?

**Comment by tprrt** [comment]
This issue is no longer relevant.
