### ISSUE TITLE
Why Do not support Spike anymore

### ISSUE THREAD

**Issue by Phantom1003** [sifive/freedom-u-sdk#132]
I noticed that after v1 spike isn't support by U sdk anymore, is there some reason ? thanks

**Comment by jim-wilson** [comment]
spike very limited support for devices, and can't support u-boot.  linux without u-boot isn't interesting anymore.

Also, as with all things, something remains supported only if someone is willing to support it.  And there is unfortunately no one volunteering their time to support this.

**Comment by Phantom1003** [comment]
https://github.com/Phantom1003/RISC-V-Spike-Simulator-SDK
