### ISSUE TITLE
What is the address space division of freedom u500 Linux? What space does not pass TLB?

### ISSUE THREAD

**Issue by ImagineMiracle-wxn** [sifive/freedom-u-sdk#135]
What is the address space division of freedom u500 Linux? What space does not pass TLB?

**Comment by jim-wilson** [comment]
You can find a hardware memory map in the Freedom U540-C000 docs at sifive.com/documentation see chapter 5.

If this is a linux kernel question, then maybe try asking on the linux-riscv mailing list.
