### ISSUE TITLE
SiFive unmatched failed to poweroff

### ISSUE THREAD

**Issue by sequencer** [sifive/freedom-u-sdk#143]
In the unmathced A00 version.
After poweroff, power doesn't off, which needs a manually push power button to poweroff.
Is this issue reproducible in other unmatched?
I think this is a opensbi issue but no idea to debug.

**Comment by davidlt** [comment]
This is expected. The reset and poweroff is not yet implemented in the FW (WIP).

**Comment by sequencer** [comment]
Thanks!
