### ISSUE TITLE
TPE-M2NCRD WiFi and Bluetooth card not working

### ISSUE THREAD

**Issue by GarethH96** [sifive/freedom-u-sdk#149]
I have a M.2 NGFF WiFi and Bluetooth card with the model number: TPE-M2NCRD. It has the Atheros AR9462 chip set, which I believe uses the `ath9k` kernel module. Bluetooth will enable, but my smartphone cannot see the SiFive HiFive Unmatched and vice versa. Meanwhile, WiFi doesn't work at all as the Xfce4 network manager applet doesn't see anything.

**Edit:** Kernel was using the `ath3k` module for the device, so I enabled `CONFIG_ATH9K`, `CONFIG_ATH9K_HTC `, and`CONFIG_CARL9170` modules in `meta-sifive/recipes-kernel/linux/files/defconfig`. Then, blacklisted `ath3k` in `/etc/modprobe.d/blacklist.conf` and added `ath9k` to `/etc/modules-load.d/ath9k.conf`. Now, the Bluetooth icon doesn't even show up in the system tray. `lsmod` displays `ath9k`  as enabled, but `lspci` doesn't show anything using the `ath9k` module.

**Comment by tprrt** [comment]
This issue is no longer relevant.
