### ISSUE TITLE
How to build with modified OpenSBI?

### ISSUE THREAD

**Issue by macromogic** [sifive/freedom-u-sdk#150]
Hi SiFive,
I want to test the behavior of a modified OpenSBI on the HiFive Unmatched board, but I have no idea how to put my code and build the image. Is it possible to do that?

**Comment by sh1r4s3** [comment]
I'm not sure but probably you could edit the `meta-sifive/recipes-bsp/opensbi/opensbi_0.9.bb` file. Add your patches in the same way or replace URL to your git repo.
