### ISSUE TITLE
No official build for 2022.05 and 2022.06?

### ISSUE THREAD

**Issue by zhangboyang** [sifive/freedom-u-sdk#171]
I saw there are [branches](https://github.com/sifive/freedom-u-sdk/branches) for `2022.05` and `2022.06`, but the latest [release](https://github.com/sifive/freedom-u-sdk/releases) is `2022.04.00`. Is this a bug or feature? :)

**Comment by tprrt** [comment]
Hello @zhangboyang,
Assets of the release 2022.06.00 are now available.
