### ISSUE TITLE
2022.06 kas build error

### ISSUE THREAD

**Issue by JuFly** [sifive/freedom-u-sdk#173]
Error while executing `kas build freedom-u-sdk/scripts/kas/qemuriscv64-cli.yml`
[log.do_configure.2796418.txt](https://github.com/sifive/freedom-u-sdk/files/9745628/log.do_configure.2796418.txt)

**Comment by alexandrebelloni** [comment]
The issue you have is that you can't connect to github:

Failed to connect to github.com port 443: Connection timed out

You can either retry or fix your connectivity
