### ISSUE TITLE
freedom-u-sdk 2022.06 build  qemuriscv64-cli.yml

### ISSUE THREAD

**Issue by ChildeHui12138** [sifive/freedom-u-sdk#175]
I  execute kas build freedom-u-sdk/scripts/kas/qemuriscv64-cli.yml
then there is one tast failured. the log is as following:
ERROR: Task (/home/wdh/riscv-sifive/build/../meta-tensorflow-lite/recipes-framework/tensorflow-lite/libtensorflow-lite_2.9.0.bb:do_configure) failed with exit code '1'
I learned that this error shows there is something wrong with doing configure in the Yocto project‘s recipes.

**Comment by tprrt** [comment]
It is duplicate of #173 and #174.
