### ISSUE TITLE
TensorFlow and Pytorch on unmatch machines

### ISSUE THREAD

**Issue by abadouh** [sifive/freedom-u-sdk#177]
Hi,
I am trying to run genomics benchmarks on Unmatched board with Fedora.
In order to do so, I need to install pytorch and Tensorflow.

In order to build Tensorflow there are dependencies of Bazel and java (JDK) for RISC-V.

By any chance someone manage to install these framework on the unmatched with fedora?

Kind regards,
Asaf

**Comment by tprrt** [comment]
No relation to the FUSDK.
