### ISSUE TITLE
No 'apt' or 'apt-get'

### ISSUE THREAD

**Issue by alitariq4589** [sifive/freedom-u-sdk#178]
Hello all,
I have followed all the instructions and built `2022.10` freedom-u-sdk for my hifive unleashed. But there is no `apt` or `apt-get` package here. So, how can I install packages on it. Also kindly tell me what distro it is. I am seeing freedomusdk everywhere. There are `dnf` and `rpm` though, which indicate that it is fedora-like distro. A helpful answer will be appreciated.

UPDATE:  When I try to update repositories using `dnf update` with root privileges, I get following error:
```
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```
Kindly also purpose a workaround for this error

Regards,
Ali

**Comment by tprrt** [comment]
Depreciated
