### ISSUE TITLE
fu740 pcie window too small

### ISSUE THREAD

**Issue by bjdooks-sifive** [sifive/freedom-u-sdk#179]
The pcie window for the fu740 SoC (Unmatched) is a 1/16th of the size it should be, which causes issues with certain pcie cards.
Fix is currently being queued for both next and stable here: https://git.kernel.org/pub/scm/linux/kernel/git/conor/linux.git/commit/?id=43d5f5d63699724d47f0d9e0eae516a260d232b4

**Comment by tprrt** [comment]
Should be fixed.
