### ISSUE TITLE
FUSDK 2023.06.00 build breaks while trying to build trace-cmd

### ISSUE THREAD

**Issue by nylon7** [sifive/freedom-u-sdk#183]
Hi @tprrt ,

FUSDK 2023.06.00 build is broken for Unmatched.  The trace-cmd package doesn’t build.  This happens on both the Linux cluster and on my Debian laptop.

Have you encountered any problems?

**Comment by tprrt** [comment]
Hello @nilon7,

I'm unable to reproduce this issue, my builds are successful. Can you tell me more ?

Kind regards,
Thomas
