### ISSUE TITLE
Build 32-bit target failed

### ISSUE THREAD

**Issue by kting93** [sifive/freedom-u-sdk#23]
Hi, 

I am trying to build 32-bit target from freedom-u-sdk. The build of 64-bit target works well but the 32-bit failed. What I am doing is modifying the Makefile and changed the variables 

ISA ?= rv32ima
ABI ?= ilp32

Then type make linux and I got no rule to make target error:

![image](https://user-images.githubusercontent.com/35649620/35207132-2c9442b4-fef6-11e7-99c7-41f1b9a85ef7.png)

Please help to point out what I am doing wrong. 

Thanks in advance, 
Kai-Yuan

**Comment by jim-wilson** [comment]
32-bit builds aren't supported yet.  The ISA and ABI variables are relatively new and untested.  Only very minor changes to them are likely to work.

**Comment by kting93** [comment]
Hi Jim,

Thanks for your reply. Looks like I have to manually configure and build the gcc, linux, buildroot, spike, bbl and qemu to run in 32-bit mode. 

Thanks,
Kai-Yuan
