### ISSUE TITLE
An error occurred in the new version using make all

### ISSUE THREAD

**Issue by LiHao217** [sifive/freedom-u-sdk#32]
I downloaded the latest version, did not change Makefile, and then I used make all to build it with the following errors. 
It looks like the library file could not be found while compiling the linux kernel. Where is the path configuration error? 
How do I fix it?
![qq 20180215175259](https://user-images.githubusercontent.com/26959371/36250612-514697d8-1279-11e8-84d1-a96feb57a5a5.jpg)
![image](https://user-images.githubusercontent.com/26959371/36250835-efa2e17a-1279-11e8-9b40-6900bf791d18.png)
@jim-wilson Hi,jim.I need your help again,thank you.
And It's the new year in China now,happy new year to you.

**Comment by jim-wilson** [comment]
This is a host tool using host libraries.  So you need to install another package on your host system.  Depending on your OS, I think it should be something like libssl-dev (ubuntu) or openssl-devel (fedora). 
Maybe the new linux kernel version is enabling a feature that wasn't enabled before.

**Comment by tprrt** [comment]
This issue no longer occurs.
