### ISSUE TITLE
Compatible Rocket Chip Commit for Multicore?

### ISSUE THREAD

**Issue by lucashmorais** [sifive/freedom-u-sdk#45]
Hi there,

I am starting to develop an accelerator for the Rocket Chip using its RoCC interface, but it has been a bit difficult to find a combination of versions for rocket-chip/riscv-tools/riscv-linux that works for multicore configurations of that SoC. On the other hand, the latest hifiveu-1.0-2018-03-20 release of this repository seems very promising.

That said, does anyone know a commit from Rocket Chip that is guaranteed to work with this latest release tag?

Besides, am I right to suppose that both the riscv-gnu-toolchain and riscv-linux repos here submoduled already target priv-1.10?

I would be immensely grateful for any help with this, as the process of checking out commits, configuring Linux, compiling everything, generating a bitstream and testing on the board does take some time x)

**Comment by terpstra** [comment]
priv-1.10 has been merged to master in all repositories quite some time ago.

The master branch on all the repositories should be compatible with each other.
