### ISSUE TITLE
Error: "unable to execute program：(abstractcs=0x10000301)"  when use command "make run_openocd...."

### ISSUE THREAD

**Issue by Pengnian** [sifive/freedom-u-sdk#5]
Hi,all

When I use command "make run_openocd ........" to debug  demo program encountered  that  error, how  to  fix ?
![starting_openocd](https://user-images.githubusercontent.com/26727603/28497796-c3378664-6fc1-11e7-9a57-de5e34dd201e.png)

**Comment by mwachs5** [comment]
It's not actually an error, it's just part of the normal OpenOCD flow. But agree that it is confusing. See https://github.com/riscv/riscv-openocd/issues/46
