### ISSUE TITLE
Linux boot stuck up (bootconsole [early0] disabled)

### ISSUE THREAD

**Issue by billasurendra** [sifive/freedom-u-sdk#73]
After executing the command "make sim", Linux started booting and stuck up by showing the following lines.

[    0.130295] io scheduler noop registered
[    0.130855] io scheduler cfq registered (default)
[    0.131405] io scheduler mq-deadline registered
[    0.131935] io scheduler kyber registered
[    0.353880] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    0.357210] libphy: Fixed MDIO Bus: probed
[    0.357760] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.358520] ehci-pci: EHCI PCI platform driver
[    0.359080] usbcore: registered new interface driver usb-storage
[    0.359915] usbcore: registered new interface driver usbhid
[    0.360565] usbhid: USB HID core driver
[    0.361185] NET: Registered protocol family 17
[    0.363445] bootconsole [early0] uses init memory and must be disabled even before the real one is ready
**[    0.364545] bootconsole [early0] disabled**

Please some one help to resolve this problem.

**Comment by jim-wilson** [comment]
The default serial driver is the one that works best on the HiFive Unleashed board.  It unfortunately does not work in spike.  To get spike working, you need to enable 
CONFIG_HVC_RISCV_SBI=y
in conf/linux_defconfig and rebuild.

**Comment by billasurendra** [comment]
Thank you so much my problem is resolved

**Comment by sbates130272** [comment]
I had a similar issue. Can't we add CONFIG_HVC_RISCV_SBI=y to the linux_defconfig? It surely does not conflict with the other options for serial consoles?

**Comment by jim-wilson** [comment]
It does conflict.  If you enable CONFIG_HVC_RISCV_SBI, then you get the wrong console when booting on a hifive unleashed board.  We care more about support for the hifive unleashed board than we do about support for spike, to it is disabled by default.

**Comment by lsw8075** [comment]
I have same issue when 'make sim', but found CONFIG_HVC_RISCV_SBI=y is already enabled in conf/linux_defconfig. What can I do to resolve the problem?

...
[    0.000000] console [tty0] enabled
[    0.000000] bootconsole [early0] disabled
