### ISSUE TITLE
Compilation issue with 'make qemu'

### ISSUE THREAD

**Issue by amaier17** [sifive/freedom-u-sdk#77]
I'm trying to build the qemu model with freedom sdk but I'm getting this error at the end:

>>> libtirpc 1.0.1 Autoreconfiguring
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /home/users/amaier/freedom-u-sdk/work/buildroot_initramfs/host/usr/bin/automake line 3936.
autoreconf: /home/users/amaier/freedom-u-sdk/work/buildroot_initramfs/host/usr/bin/automake failed with exit status: 255
package/pkg-generic.mk:185: recipe for target '/home/users/amaier/freedom-u-sdk/work/buildroot_initramfs/build/libtirpc-1.0.1/.stamp_configured' failed
make[1]: *** [/home/users/amaier/freedom-u-sdk/work/buildroot_initramfs/build/libtirpc-1.0.1/.stamp_configured] Error 1
make[1]: Leaving directory '/home/users/amaier/freedom-u-sdk/buildroot'
Makefile:90: recipe for target '/home/users/amaier/freedom-u-sdk/work/buildroot_initramfs/images/rootfs.tar' failed
make: *** [/home/users/amaier/freedom-u-sdk/work/buildroot_initramfs/images/rootfs.tar] Error 2

**Comment by jim-wilson** [comment]
This is a versioning issue.  A warning in an older version of perl changed to an error in a more recent version of perl.  We use Ubuntu 16.04 here, and this code works OK on this version of Ubuntu.

There is a buildroot branch mjc/fix-glibc-2.27-perl-5.26 which has a fix for this issue and a glibc versioning issue.  I think it is Ubuntu 18.04 that this branch is known to work on.  You can try checking out this branch of buildroot, and then don't run git submodule at the top level again or it will give you the default buildroot back.

**Comment by amaier17** [comment]
Thanks Jim! Looks like I was able to install it after fixing the versioning issue though I've reverted back to 16.04 for now.
