### ISSUE TITLE
failed to boot because of the large image size

### ISSUE THREAD

**Issue by Ddnirvana** [sifive/freedom-u-sdk#78]
Hi guys,
     I can boot the Linux use the freedom-u-sdk(commit# af61d6d2) on U500 (VC707 FPGA board). 
     However, when I am adding a simple test program, like helloworld in the ramdisk, it will hang after printing the "SiFive RISC-V  Core IP" logo.
     I checked that the compiled helloworld occupies 4MB (since I add `-static` flag during compilation). And the size of  bbl.bin becomes from 16M to 20MB.
     I have tried to add a simple hello.c file in the ramdisk, and it succeeds.

  It seems the bbl has some requirement about the image size?
  Any advices to solve this issue?

**Comment by jim-wilson** [comment]
The U500/VC707 boot loader only reads the first 16MB.  See for instance
https://forums.sifive.com/t/building-linux-for-custom-u500/208

**Comment by terpstra** [comment]
Increase PAYLOAD_SIZE in freedom/bootrom/sdboot/sd.c:13

In the future, I'd like this bootloader to be replaced with the now open-source FSBL used by the SiFive U540, but there is no ETA on when that will land.

**Comment by Ddnirvana** [comment]
Thanks for you two guys' help!

Increasing the PAYLOAD_SIZE in freedom/bootrom/sdboot/sd.c solves my problem :)
